/**
 * Conan.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Video { 
    readonly id?: string | null;
    readonly createdAt?: number;
    readonly updatedAt?: number;
    readonly domainEvents?: Array<object> | null;
    title?: string | null;
    isTV?: boolean;
    seqId?: number;
    publish?: number;
    biliPlayId?: string | null;
}

